@extends('front.layouts.app')

@section('content')
<div class="col-md-10 col-md-offset-1"><br>
    <center><h2><strong>PETUNJUK BAN MOTOR</strong></h2></center>
    <p>Pada kendaraan roda dua maupun roda empat, ban adalah salah satu komponen yang sangat penting, karena berhubungan langsung dengan aspal jalanan. Pada komponen itulah kenyamanan, keselamatan, pengendalian, akselerasi, pengereman dan berapa luas area tapak ban yang menempel pada jalan akan memberikan keamanan pada pengendara.</p><br/>
    <p>Hal ini penting manakala kita akan mengganti ban kendaraan entah itu modifikasi atau karena ban aus, ini yang harus diperhatikan. Pada saat kita akan mengganti ban kendaraan, biasanya kita hanya mengatakan ukuran ban yang akan kita ganti atau beli, misal ukuran 2.75-17 atau 100/90-18. Karena secara umum parameter itu menunjukan ukuran lebar, tebal dan diameter, tetapi sesungguhnya masih banyak kode maupun symbol yang harus bikers ketahui agar mendapat ban yang sesuai dengan spesifikasi yang dinginkan serta mengetahui batasan-batasan yang aman untuk pemakaian.</p>
    <p>Kita simak dari bagian yang paling umum dahulu untuk standar sebuah ban.<br /> <br />
    <strong><u>UKURAN</u></strong><br />
    Ukuran pada ban terdiri dari dua jenis yaiut ukuran&nbsp;metric&nbsp;dan&nbsp;inchi</p>
    <p>Metric<br /> 80/90-17&nbsp;memiliki arti: Ban ini memiliki lebar 80mm dengan tinggi dinding ban 72mm dan menggunakan velg ukuran 17 inchi.<br /> <br /> Ini penjabarannya:<br /> 80&nbsp;[lebar ban dalam satuan mm] : adalah ukuran bagian terlebar dari ban dengan nilai +/- 80mm.<br /> 90&nbsp;[Aspek rasio] : adalah &nbsp;persentase dari lebar ban atau sama dengan 80 X 90% = 72mm.<br /> 17&nbsp;[diameter velg] : adalah ukuran diameter velg yang harus digunakan.</p>
    <p>Inchi<br /> 2.75-17&nbsp;memiliki arti: Ban ini memiliki lebar 2,75 inchi dengan tinggi dinding 2.75 inchi dan menggunakan velg ukuran 17 inchi.<br /> <br /> Ini penjabarannya:<br /> 2.75&nbsp;[lebar ban dalam satuan inchi] : adalah ukuran bagian terlebar dari penampang ban dengan nilai +/- 2.75 inchi dan tinggi 2.75 inchi.<br /> 17&nbsp;[diameter velg] : adalah ukuran diameter velg yang harus digunakan.</p>
    <p><strong><u>TWI [TREAD WEAR INDICATOR]</u></strong></p>
    <p>ini adalah simbol untuk menunjukan batas pemakaian ban. Tandanya berupa tonjolan pada sela-sela patern ban dan tanda segitiga yang tertera pada dinding ban. Hal ini menunjukan batas keausan tread yang diijinkan oleh produsen untuk menjamin performa ban, jika keausan tread sudah mencapai tanda ini maka sebaiknya ban segera diganti.</p>
    <p><strong><u>TUBELESS/TUBE TYPE</u></strong></p>
    <p>Tubeless:&nbsp;adalah jenis ban yang aplikasinya diperbolehkan tanpa menggunakan ban dalam dengan ketentuan harus menggunakan velg castwheel type tubeless dengan ukuran yang sesuai dengan ban nya dan harus menggunakan pentil khusus tubeless.<br /> Tube Type:&nbsp;adalah jenis ban yang pada aplikasinya harus menggunakan ban dalam.</p>
    <p><u>LOT NUMBER</u></p>
    <p>Lot number adalah kode yang menunjukan waktu diproduksinya ban tersebut.<br /> Umumnya terdapat 4 angka yang menunjukan minggu dan tahun. Dua angka depan menunjukan minggu dan dua angka akhir menunjukan tahun.<br /> Kalaupun ada ada yg lebih dari 4 huruf atau terdapat huruf lain didepannya, 4 angka terakhir tetap menunjukan minggu dan tahun.<br /> Angka 2607 pada gambar memiliki arti: ban diproduksi pada minggu ke 26 tahun 2007</p>
    <p><strong><u>SPEED SIMBOL &amp; LOAD INDEX</u></strong></p>
    <p>Kode ini untuk menunjukan batas kecepatan maksimun dan beban maksimum yang dianjurkan.<br /> Kode&nbsp;41P&nbsp;artinya: beban maksimum untuk ban tersebut adalah 145 kg dan kecepatan maksimum untuk ban tersebut adalah 150 km/jam<br /> kode 41: untuk beban maksimum 145kg<br /> kode P: untuk kecepatan 150 km/jam</p>
    <p>INDEX BEBAN &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;INDEX SPEED<br /> <u>KODE &nbsp; &nbsp;BEBAN</u>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<u>&nbsp;KODE &nbsp; &nbsp; SPEED</u><br /> 30 &nbsp; &nbsp; &nbsp; &nbsp;106 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;B &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 50 km/jam<br /> 31 &nbsp; &nbsp; &nbsp; &nbsp;109 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;C &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 60 km/jam<br /> 32 &nbsp; &nbsp; &nbsp; &nbsp;118 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;D &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 65 km/jam<br /> 33 &nbsp; &nbsp; &nbsp; &nbsp;115 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;E &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 70 km/jam<br /> 38 &nbsp; &nbsp; &nbsp; &nbsp;132 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;F &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 80 km/jam<br /> 40 &nbsp; &nbsp; &nbsp; &nbsp;140 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;G &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 90 km/jam<br /> 41 &nbsp; &nbsp; &nbsp; &nbsp;145 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;J &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 100 km/jam<br /> 42 &nbsp; &nbsp; &nbsp; &nbsp;150 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;K &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 110 km/jam<br /> 43 &nbsp; &nbsp; &nbsp; &nbsp;155 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;L &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 120 km/jam<br /> 44 &nbsp; &nbsp; &nbsp; &nbsp;160 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;M &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;130 km/jam<br /> 45 &nbsp; &nbsp; &nbsp; &nbsp;165 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;N &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;140 km/jam<br /> 46 &nbsp; &nbsp; &nbsp; &nbsp;170 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;P &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;150 km/jam<br /> 47 &nbsp; &nbsp; &nbsp; &nbsp;175 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;T &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;190 km/jam<br /> 48 &nbsp; &nbsp; &nbsp; &nbsp;180 kg &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;U &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;200 km/jam</p>
    <p><u>ANAK PANAH</u></p>
    <p>Anak panah menunjukan arah putaran ban, agar ban berfungsi dengan baik.</p>
    <p>Nah ini sekilas informasi umum tentang kode dan simbol yang ada pada ban. Jadi jangan sampe salah beli ban, seperti salah ukuran lebar ban atau salah pilih index beban dan index speed nya dan jangan sampe beli ban yg sudah kadaluarsa...</p>
    <p>&nbsp;</p>
</div>
@endsection
